const AdvancedArrayFiltering = {};


// ============================================================================
// Task 1: Advanced Array Filtering
// ============================================================================

/**
 * Filters an array to keep only unique elements based on a value
 * generated by a callback function.
 *
 * @param {Array<any>} arr The array to filter.
 * @param {Function} callback A function that takes an element and returns a value to check for uniqueness.
 * @returns {Array<any>} A new array containing only the unique elements.
 */
AdvancedArrayFiltering.customFilterUnique = (array, callback) => {

    const seenItems = new Set();
   
    // In order to complete this assignment I use the built-in filter method
    // and a Set to track seen items based on the value returned by the callback.
    // The callback function is applied to each item in the array to determine its uniqueness
    return array.filter(item => {
        const valueKey = callback(item);

        if(seenItems.has(valueKey)) {
            // If the valueKey is already in the seenItems set, then that means the value is not unique
            // and it should not be included in the filtered array
            // That's why the function returns false
            return false;
        }else {
            // If the valueKey is not in the seenItems set, then it must be added and return true
            seenItems.add(valueKey);
            return true;
        }
    })
};


// ============================================================================
// Task 2: Array Chunking
// ============================================================================
/**
 * Divides an array into smaller arrays (chunks) of a specified size.
 *
 * @param {Array<any>} arr The array to chunk.
 * @param {number} size The size of each chunk. Must be a positive integer.
 * @returns {Array<Array<any>>} An array of arrays (the chunks).
 */


AdvancedArrayFiltering.chunkArray = (array, chunkSize) => {

    // Checks if the chunkSize is a valid positive integer
    if(chunkSize <= 0) {
        throw new Error("Invalid chunk size");
    }

    const chunks = [];

    for(let i = 0; i < array.length; i += chunkSize){
        // The slice method is used to create a sub-array by indicating the start and end indices
        // The end index is i + chunkSize, which means it will take the next chunk
        // If the end index exceeds the length of the array, then the slice method will automatically adjust 
        // to take only the remaining elements
        const chunkedArray = array.slice(i, i + chunkSize);
        chunks.push(chunkedArray)
    }

    return chunks;

};

// ============================================================================
// Task 3: Array Shuffling
// ============================================================================

/**
 * Creates a new array with the elements of the input array shuffled randomly.
 * Implements the Fisher-Yates (also known as Knuth) shuffle algorithm for
 * efficient and uniform shuffling.
 *
 * @param {Array<any>} arr The array to shuffle.
 * @returns {Array<any>} A new array with the elements shuffled.
 */

AdvancedArrayFiltering.customShuffle = (array) => {
    // Create a copy of the original array to avoid modifying it 
    const shuffledArray = [...array];
    let currentIndex = shuffledArray.length;


    while(currentIndex !==0) {

        // I need to generate a random index from 0 to currentIndex - 1
        const randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex--;

        // Swap the current element with the element at the random index
        // This is done using destructuring assignment to swap the values
        // This ensures that each element has an equal probability of being in any position
        // The randomIndex is generated using Math.random() to get a random number between 0 and currentIndex - 1
        // The currentIndex is decremented to ensure that the next iteration will not include the currentIndex  
        [shuffledArray[currentIndex], shuffledArray[randomIndex]] = [shuffledArray[randomIndex], shuffledArray[currentIndex]];
    }

    return shuffledArray;
};


// ============================================================================
// Task 4: Array Intersection and Union
// ============================================================================

/**
 * Finds the common elements between two arrays.
 *
 * @param {Array<any>} arr1 The first array.
 * @param {Array<any>} arr2 The second array.
 * @returns {Array<any>} A new array containing elements present in both arr1 and arr2.
 */

AdvancedArrayFiltering.getArrayIntersection = (array1, array2) => {
    // Using a Set to store the elements of the first array for efficient lookup
    // Then the filter method is used to iterate over the second array
    // and check if the element exists in the Set created from the first array
    const set1 = new Set(array1);
    return array2.filter(element => set1.has(element));
}

AdvancedArrayFiltering.getArrayUnion = (array1, array2) => {

    // This combines both arrays into a new array
    // The spread operator is used to concatenate the two arrays
    // This will include all the elements from both arrays
    const combinedArray = [...array1, ...array2];

    // First a new Set object is created taking the combined array as an argument
    // This will automatically remove any duplicate elements on its own
    // Array.from is then used to convert the Set back into an array because that's what should be returned

    return Array.from(new Set(combinedArray));
};

// ============================================================================
// Task 5: Array Performance Analysis
// ============================================================================

/**
 * Measures the execution time of a function.
 *
 * @param {Function} func The function to measure.
 * @param {any} ...args The arguments to pass to the function.
 * @returns {number} The execution time in milliseconds.
 */

AdvancedArrayFiltering.measureArrayPerformance = (func, ...args) => {
    
    const startTime = performance.now();
    func(...args);
    const endTime = performance.now();

    return endTime - startTime;
};

export default AdvancedArrayFiltering;